
// note that we don't actually use any of this crap except on the fallback path

#include "chars.h"

skill 5
{
	CHARACTERISTIC_NAME				"aph"
	CHARACTERISTIC_GENDER			"male"
	CHARACTERISTIC_ATTACK_SKILL		1.0
	CHARACTERISTIC_WEAPONWEIGHTS	"bots/aph_w.c"
	CHARACTERISTIC_AIM_SKILL		1.0
	CHARACTERISTIC_AIM_ACCURACY		1.0
	CHARACTERISTIC_VIEW_FACTOR		0.99
	CHARACTERISTIC_VIEW_MAXCHANGE	360
	CHARACTERISTIC_REACTIONTIME		0.9

	CHARACTERISTIC_CHAT_FILE			"bots/aph_t.c"
	CHARACTERISTIC_CHAT_NAME			"aph"
	CHARACTERISTIC_CHAT_CPM				100.0
	CHARACTERISTIC_CHAT_INSULT			0.0
	CHARACTERISTIC_CHAT_MISC			0.0
	CHARACTERISTIC_CHAT_STARTENDLEVEL	1.0
	CHARACTERISTIC_CHAT_ENTEREXITGAME	0.0
	CHARACTERISTIC_CHAT_KILL			0.0
	CHARACTERISTIC_CHAT_DEATH			0.0
	CHARACTERISTIC_CHAT_ENEMYSUICIDE	0.0
	CHARACTERISTIC_CHAT_HITTALKING		0.0
	CHARACTERISTIC_CHAT_HITNODEATH		0.0
	CHARACTERISTIC_CHAT_HITNOKILL		0.0
	CHARACTERISTIC_CHAT_RANDOM			0.0
	CHARACTERISTIC_CHAT_REPLY			0.0

	CHARACTERISTIC_CROUCHER				0.0
	CHARACTERISTIC_JUMPER				0.5
	CHARACTERISTIC_WEAPONJUMPING		1.0
	CHARACTERISTIC_GRAPPLE_USER			0.0

	CHARACTERISTIC_ITEMWEIGHTS			"bots/aph_i.c"
	CHARACTERISTIC_AGGRESSION			0.95
	CHARACTERISTIC_SELFPRESERVATION		0.9
	CHARACTERISTIC_VENGEFULNESS			0.9
	CHARACTERISTIC_CAMPER				0.1

	CHARACTERISTIC_EASY_FRAGGER			0.0
	CHARACTERISTIC_ALERTNESS			1.0

	CHARACTERISTIC_AIM_ACCURACY_MACHINEGUN		0.9
	CHARACTERISTIC_AIM_ACCURACY_SHOTGUN			1.0
	CHARACTERISTIC_AIM_ACCURACY_ROCKETLAUNCHER	0.95
	CHARACTERISTIC_AIM_ACCURACY_GRENADELAUNCHER	0.9
	CHARACTERISTIC_AIM_ACCURACY_LIGHTNING		0.75
	CHARACTERISTIC_AIM_ACCURACY_PLASMAGUN		1.0
	CHARACTERISTIC_AIM_ACCURACY_RAILGUN			1.0
	CHARACTERISTIC_AIM_ACCURACY_BFG10K			1.0
	CHARACTERISTIC_AIM_SKILL_ROCKETLAUNCHER		1.0
	CHARACTERISTIC_AIM_SKILL_GRENADELAUNCHER	1.0
	CHARACTERISTIC_AIM_SKILL_PLASMAGUN			1.0
	CHARACTERISTIC_AIM_SKILL_BFG10K				1.0

	CHARACTERISTIC_FIRETHROTTLE					1.0
}
